

name: Selenium Prometheus Monitoring for UI Tests

on:
  push:
    branches: '**'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    uses: jeeshan12/resusable_workflows/.github/workflows/selenium.yml@main
    with:
      fileName: testng.xml
