

name: Selenium Prometheus Monitoring for UI Tests

on:
  push:
    branches: '**'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    uses: jeeshan12/resusable_workflows/.github/workflows/selenium.yml@main
    with:
      fileName: testng.xml
  monitoring:
     needs: test
     if: always()
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: actions/download-artifact@v3
         with:
            name: test-results
       - name: Collect Ressults
         env:
          PUSHGATEWAY_IP: ${{ secrets.PUSHGATEWAY_IP }}
         run : |
           ls /home/runner/work/SeleniumPrometheusIntegration/SeleniumPrometheusIntegration
           cat ${GITHUB_WORKSPACE}
           sh test_status.sh testng-results.xml
         
      
     
